### ISSUE TITLE
Got an "panic: interface conversion: interface {} is nil, not string" error when scanning, which killed the whole job.

### ISSUE THREAD

**Issue by S4lt5** [DevSecOpsDocs/nuclearpond#6]
I saw the following when running a broad scan, I have not narrowed down the cause yet but figured I would get a dialogue going.
This was at approx host 900 out of a list of ~35000.

```console
panic: interface conversion: interface {} is nil, not string

goroutine 230 [running]:
github.com/DevSecOpsDocs/nuclearpond/pkg/outputs.S3Output({0x0?, 0x0?})
	/home/vnc/nuclearpond/pkg/outputs/outputs.go:15 +0xfe
github.com/DevSecOpsDocs/nuclearpond/pkg/lambda.InvokeLambdas({{0xc000720c40, 0x1, 0x913c}, {0xc000700040, 0x2, 0x2}, {0x7fffce3b162b, 0x2}}, {0x7fffce3b15c1, 0x19}, ...)
	/home/vnc/nuclearpond/pkg/lambda/lambda.go:50 +0x1fd
github.com/DevSecOpsDocs/nuclearpond/pkg/core.ExecuteScans.func2()
	/home/vnc/nuclearpond/pkg/core/core.go:50 +0x5c
github.com/DevSecOpsDocs/nuclearpond/pkg/core.ExecuteScans.func1()
	/home/vnc/nuclearpond/pkg/core/core.go:32 +0x7a
created by github.com/DevSecOpsDocs/nuclearpond/pkg/core.ExecuteScans
	/home/vnc/nuclearpond/pkg/core/core.go:29 +0xad
```

**Comment by S4lt5** [comment]
I  *think* I've seen this before when nuclei exits with an error,  and the s3 parser chokes on it.

I'm adding a nil check locally and see if I encounter further problems
